name: Create Release

on:
  push:
    branches:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/heads/}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build -t kolzchut-dashboard:${{ steps.get_version.outputs.VERSION }} .
          docker push kolzchut-dashboard:${{ steps.get_version.outputs.VERSION }}
          # Also push as 'latest'
          docker tag kolzchut-dashboard:${{ steps.get_version.outputs.VERSION }} kolzchut-dashboard:latest
          docker push kolzchut-dashboard:latest


      - name: Update release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          IMAGE_NAME="kolzchut-dashboard:${{ steps.get_version.outputs.VERSION }}"
          RELEASE_NOTE="Docker image for this release: \`$IMAGE_NAME\`"
          gh release edit ${{ steps.get_version.outputs.VERSION }} --notes "$RELEASE_NOTE"