name: Docker Build

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          RELEASE_TAG=${GITHUB_REF#/tags/}
          docker build -t kolzchut-dashboard:$RELEASE_TAG .
          docker push kolzchut-dashboard:$RELEASE_TAG
          # Also push as 'latest'
          docker tag kolzchut-dashboard:$RELEASE_TAG kolzchut-dashboard:latest
          docker push kolzchut-dashboard:latest
          

      - name: Update release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_TAG=${GITHUB_REF#/tags/}
          IMAGE_NAME="kolzchut-dashboard:$RELEASE_TAG"
          RELEASE_NOTE="Docker image for this release: \`$IMAGE_NAME\`"
          gh release edit $RELEASE_TAG --notes "$RELEASE_NOTE"
